Update student-discounts.md
Ac-Wiki/AcWiKi pull request #98
Opened 2024-11-22 16:06 UTC by flash555588

2024-11-22 16:42 UTC, ztm0929 requested changes

2024-11-22 16:42 UTC, ztm0929 commented on docs/01-student-discounts/student-discounts.md
> +- 麦当劳APP/小程序：麦当劳为大学生提供了O麦金会员学生乐享版，学生可以以优惠价格购买会员，享受包括早餐、正餐、下午茶和夜宵在内的多项权益。学生可以通过麦当劳APP或小程序完成学生身份验证后购买
麦当劳重复辽

@flash555588

2024-11-22 16:43 UTC, flash555588 commented on docs/01-student-discounts/student-discounts.md
> +- 麦当劳APP/小程序：麦当劳为大学生提供了O麦金会员学生乐享版，学生可以以优惠价格购买会员，享受包括早餐、正餐、下午茶和夜宵在内的多项权益。学生可以通过麦当劳APP或小程序完成学生身份验证后购买
好的，删除吧

2024-11-23 00:46 UTC, ztm0929 approved these changes

2024-11-23 00:46 UTC, merged